{{- if and .Values.search.security.enabled (not .Values.search.security.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "search.fullname" . }}-api-key
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "search.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.search.security.apiKey | b64enc | quote }}
{{- end -}}